version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .production.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:prod
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:16
    env_file:
      - .production.env
    environment:
      PG_DATA: /PostgreSQL/16/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/PostgreSQL/16/data
    restart: always
volumes:
  pgdata:
