services:
  main:
    image: empr10n/campus
    container_name: main
    build:
      context: .
    env_file:
      - .production.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:prod
