version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .production.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:prod
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:16
    env_file:
      - .production.env
    environment:
      PG_DATA: /var/lob/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lob/postgresql/data
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - 5050:80
    depends_on:
      - postgres
volumes:
  pgdata:
